import { useState, useMemo } from 'react';
import { ViewContainer, SectionTitle } from '../ui/common';
import { useApp } from '../../store/AppContext';
import { 
  Download, Copy, Check, Shield, Search, Flame
} from 'lucide-react';
import { soundService } from '../../services/soundService';

interface ThreatIoC {
  id: string;
  type: 'IP_ADDRESS' | 'DOMAIN' | 'SHA256_HASH' | 'URL';
  value: string;
  threatActor: string;
  severity: 'CRITICAL' | 'HIGH' | 'MEDIUM';
  confidence: number;
  attackVector: string;
  firstSeen: string;
}

const LIVE_IOCS: ThreatIoC[] = [
  { id: 'IOC-01', type: 'IP_ADDRESS', value: '185.220.101.4', threatActor: 'APT29 (Cozy Bear)', severity: 'CRITICAL', confidence: 99, attackVector: 'C2 Cobalt Strike Beacon', firstSeen: '10m ago' },
  { id: 'IOC-02', type: 'IP_ADDRESS', value: '194.26.29.112', threatActor: 'Lazarus Group', severity: 'CRITICAL', confidence: 98, attackVector: 'Ransomware Exfiltration Tunnel', firstSeen: '24m ago' },
  { id: 'IOC-03', type: 'IP_ADDRESS', value: '45.154.255.89', threatActor: 'Volt Typhoon', severity: 'CRITICAL', confidence: 95, attackVector: 'SOHO Router Proxy Mesh', firstSeen: '1h ago' },
  { id: 'IOC-04', type: 'IP_ADDRESS', value: '103.145.13.7', threatActor: 'LockBit 3.0', severity: 'HIGH', confidence: 92, attackVector: 'Initial Access Broker RDP', firstSeen: '2h ago' },
  { id: 'IOC-05', type: 'IP_ADDRESS', value: '91.240.118.168', threatActor: 'APT41 (Double Dragon)', severity: 'HIGH', confidence: 94, attackVector: 'Web Shell Dropper Probe', firstSeen: '3h ago' },
  { id: 'IOC-06', type: 'DOMAIN', value: 'auth-security-update-portal.top', threatActor: 'FIN7 Phishing', severity: 'HIGH', confidence: 96, attackVector: 'Credential Harvester', firstSeen: '4h ago' },
  { id: 'IOC-07', type: 'DOMAIN', value: 'cdn-cloud-storage-sync.com', threatActor: 'APT28 (Fancy Bear)', severity: 'CRITICAL', confidence: 97, attackVector: 'Spear-Phishing Payload Host', firstSeen: '5h ago' },
  { id: 'IOC-08', type: 'SHA256_HASH', value: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', threatActor: 'BlackCat ALPHV', severity: 'CRITICAL', confidence: 100, attackVector: 'Rust Ransomware Encryptor', firstSeen: '6h ago' },
];

export default function FirewallBlocklistExporter() {
  const { themeMode } = useApp();
  const isLight = themeMode === 'light';

  const [selectedFormat, setSelectedFormat] = useState<'CISCO' | 'FORTINET' | 'PALO_ALTO' | 'AWS_WAF' | 'SURICATA' | 'CSV'>('CISCO');
  const [actorFilter, setActorFilter] = useState<string>('ALL');
  const [copied, setCopied] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');

  const ipList = useMemo(() => LIVE_IOCS.filter(i => i.type === 'IP_ADDRESS'), []);

  const filteredIoCs = useMemo(() => {
    return LIVE_IOCS.filter((ioc) => {
      const matchActor = actorFilter === 'ALL' || ioc.threatActor.includes(actorFilter);
      const matchSearch = !searchQuery || ioc.value.includes(searchQuery) || ioc.threatActor.toLowerCase().includes(searchQuery.toLowerCase());
      return matchActor && matchSearch;
    });
  }, [actorFilter, searchQuery]);

  const generateFirewallCode = () => {
    const ips = ipList.map(i => i.value);

    switch (selectedFormat) {
      case 'CISCO':
        return `! ===============================================
! Cisco ASA / Firepower Threat Defense (FTD) ACL
! Generated by CyberShield Autonomous SOC AI
! ===============================================
object-group network CYBERSHIELD_MALICIOUS_IPS
${ips.map(ip => ` network-object host ${ip}`).join('\n')}
exit

access-list OUTSIDE_IN extended deny ip object-group CYBERSHIELD_MALICIOUS_IPS any log
access-list OUTSIDE_IN extended permit ip any any
access-group OUTSIDE_IN in interface outside`;

      case 'FORTINET':
        return `# ===============================================
# Fortinet FortiGate CLI Address Object Blocklist
# Generated by CyberShield Threat Feed
# ===============================================
config firewall address
${ips.map((ip) => `  edit "IOC_${ip.replace(/\./g, '_')}"
    set subnet ${ip} 255.255.255.255
    set comment "CyberShield Automated Threat Intel Block"
  next`).join('\n')}
end

config firewall addrgrp
  edit "CYBERSHIELD_THREAT_FEED_GROUP"
    set member ${ips.map(ip => `"IOC_${ip.replace(/\./g, '_')}"`).join(' ')}
  next
end

config firewall policy
  edit 9901
    set name "DENY_CYBERSHIELD_MALICIOUS_IOCS"
    set srcintf "wan1"
    set dstintf "internal"
    set srcaddr "CYBERSHIELD_THREAT_FEED_GROUP"
    set dstaddr "all"
    set action deny
    set schedule "always"
    set service "ALL"
    set logtraffic all
  next
end`;

      case 'PALO_ALTO':
        return `# ===============================================
# Palo Alto Networks PAN-OS External Dynamic List (EDL)
# Format: IP-List / IP-Range / CIDR
# ===============================================
${ips.map(ip => `${ip}/32`).join('\n')}`;

      case 'AWS_WAF':
        return JSON.stringify({
          Name: "CyberShield-Malicious-IP-Set",
          Scope: "CLOUDFRONT",
          Description: "Autonomous blocklist synced from CyberShield Threat Intelligence",
          IPAddressVersion: "IPV4",
          Addresses: ips.map(ip => `${ip}/32`),
          Action: "BLOCK",
          Timestamp: new Date().toISOString(),
        }, null, 2);

      case 'SURICATA':
        return `# ===============================================
# Suricata / Snort Network IDS/IPS Signatures
# ===============================================
${ips.map((ip, idx) => `drop ip [${ip}] any -> $HOME_NET any (msg:"[CyberShield IDS] Malicious C2 IP Traffic Blocked (${ip})"; threshold:type limit, track by_src, count 1, seconds 60; classtype:trojan-activity; sid:${990000 + idx}; rev:1;)`).join('\n')}`;

      case 'CSV':
      default:
        return `Indicator,Type,Threat_Actor,Severity,Confidence,Attack_Vector
${filteredIoCs.map(i => `${i.value},${i.type},"${i.threatActor}",${i.severity},${i.confidence}%,"${i.attackVector}"`).join('\n')}`;
    }
  };

  const handleCopyCode = () => {
    soundService.playSuccessBeep();
    navigator.clipboard.writeText(generateFirewallCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadFile = () => {
    soundService.playSuccessBeep();
    const ext = selectedFormat === 'CISCO' ? 'cfg' : selectedFormat === 'FORTINET' ? 'conf' : selectedFormat === 'AWS_WAF' ? 'json' : selectedFormat === 'SURICATA' ? 'rules' : 'csv';
    const blob = new Blob([generateFirewallCode()], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `CyberShield_Firewall_Blocklist_${selectedFormat.toLowerCase()}_${Date.now()}.${ext}`;
    document.body.appendChild(link);
    link.click();
    link.remove();
  };

  return (
    <ViewContainer>
      <SectionTitle
        title="Enterprise Firewall IoC Blocklist Exporter"
        subtitle="1-Click export of active threat indicators formatted for Cisco ASA, Fortinet FortiGate, Palo Alto Networks, AWS WAF, and Snort"
        icon={<Flame className="w-6 h-6 text-orange-500" />}
      />

      {/* Main Grid Workspace */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Left Column: Live IoC Inventory */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h3 className={`text-xs font-display font-bold uppercase tracking-wider ${
              isLight ? 'text-slate-800' : 'text-cyan-300'
            }`}>
              Live Threat Indicators ({filteredIoCs.length})
            </h3>
            <span className="text-[10px] text-emerald-600 dark:text-emerald-400 font-bold bg-emerald-500/15 px-2 py-0.5 rounded border border-emerald-500/30">
              LIVE STIX 2.1 FEED
            </span>
          </div>

          {/* Search & Filter */}
          <div className="space-y-2">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-gray-500" />
              <input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Filter by IP, domain, hash..."
                className={`w-full pl-9 pr-3 py-1.5 rounded-xl border text-xs focus:outline-none ${
                  isLight
                    ? 'bg-white border-slate-300 text-slate-900 focus:border-cyan-600'
                    : 'bg-black/60 border-cyan-500/20 text-gray-200 focus:border-cyan-400'
                }`}
              />
            </div>

            <select
              value={actorFilter}
              onChange={(e) => setActorFilter(e.target.value)}
              className={`w-full px-3 py-1.5 rounded-xl border text-xs focus:outline-none ${
                isLight
                  ? 'bg-white border-slate-300 text-slate-900 focus:border-cyan-600'
                  : 'bg-black/60 border-cyan-500/20 text-cyan-300'
              }`}
            >
              <option value="ALL">All Threat Actor Groups</option>
              <option value="APT29">APT29 (Cozy Bear)</option>
              <option value="Lazarus">Lazarus Group</option>
              <option value="Volt Typhoon">Volt Typhoon</option>
              <option value="LockBit">LockBit 3.0</option>
              <option value="APT41">APT41</option>
            </select>
          </div>

          {/* IoC List Cards */}
          <div className="space-y-2 max-h-[500px] overflow-y-auto pr-1">
            {filteredIoCs.map((ioc) => (
              <div
                key={ioc.id}
                className={`p-3 rounded-xl border transition-all text-xs font-mono space-y-1 ${
                  isLight
                    ? 'bg-white border-slate-200 hover:border-cyan-400 text-slate-800 shadow-sm'
                    : 'bg-black/70 border-cyan-500/15 hover:border-cyan-500/30'
                }`}
              >
                <div className="flex items-center justify-between">
                  <span className="text-[10px] px-1.5 py-0.2 rounded bg-red-500/20 text-red-600 dark:text-red-400 font-bold uppercase">
                    {ioc.severity} ({ioc.confidence}%)
                  </span>
                  <span className={`text-[10px] ${isLight ? 'text-slate-500' : 'text-gray-500'}`}>{ioc.firstSeen}</span>
                </div>

                <p className={`font-bold truncate text-[11px] select-all ${isLight ? 'text-slate-900' : 'text-gray-100'}`}>{ioc.value}</p>

                <div className={`flex items-center justify-between text-[10px] pt-0.5 ${isLight ? 'text-slate-500' : 'text-gray-400'}`}>
                  <span className={`font-semibold ${isLight ? 'text-cyan-800' : 'text-cyan-300'}`}>{ioc.threatActor}</span>
                  <span className="truncate max-w-[120px] text-gray-400">{ioc.attackVector}</span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Right Column: Code Generator & Exporter */}
        <div className="lg:col-span-2 space-y-4">
          <div className={`p-5 rounded-2xl border space-y-4 shadow-md ${
            isLight ? 'bg-white border-slate-200 text-slate-800' : 'glass-panel border-cyan-500/30 bg-black/70'
          }`}>
            
            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
              <div>
                <h3 className={`text-sm font-bold uppercase tracking-wide flex items-center gap-2 ${
                  isLight ? 'text-slate-900' : 'text-white'
                }`}>
                  <Shield className={`w-4 h-4 ${isLight ? 'text-cyan-700' : 'text-cyan-400'}`} />
                  <span>Target Firewall Format Generator</span>
                </h3>
                <p className={`text-xs mt-0.5 ${isLight ? 'text-slate-600' : 'text-gray-400'}`}>
                  Select your enterprise network perimeter firewall to generate copy-paste rule syntax
                </p>
              </div>

              <div className="flex items-center gap-2">
                <button
                  onClick={handleCopyCode}
                  className={`px-3.5 py-1.5 rounded-xl border text-xs font-bold flex items-center gap-1.5 transition-all cursor-pointer ${
                    isLight
                      ? 'bg-slate-100 hover:bg-slate-200 border-slate-300 text-slate-700'
                      : 'bg-cyan-500/15 hover:bg-cyan-500/25 border-cyan-500/30 text-cyan-300'
                  }`}
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copied ? 'Copied!' : 'Copy Rules'}</span>
                </button>

                <button
                  onClick={handleDownloadFile}
                  className="px-3.5 py-1.5 rounded-xl bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 text-white font-display font-bold text-xs uppercase flex items-center gap-1.5 shadow-md cursor-pointer"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>Download File</span>
                </button>
              </div>
            </div>

            {/* Firewall Brand Tabs */}
            <div className={`flex items-center gap-1.5 p-1 rounded-xl border overflow-x-auto ${
              isLight ? 'bg-slate-100 border-slate-200' : 'bg-black/80 border-cyan-500/20'
            }`}>
              <button
                onClick={() => setSelectedFormat('CISCO')}
                className={`px-3 py-1.5 rounded-lg text-xs font-bold font-mono whitespace-nowrap transition-all cursor-pointer ${
                  selectedFormat === 'CISCO'
                    ? isLight ? 'bg-cyan-600 text-white shadow-sm' : 'bg-cyan-500 text-cyber-dark shadow-md'
                    : isLight ? 'text-slate-600 hover:text-slate-900' : 'text-gray-400 hover:text-white'
                }`}
              >
                Cisco ASA / FTD
              </button>
              <button
                onClick={() => setSelectedFormat('FORTINET')}
                className={`px-3 py-1.5 rounded-lg text-xs font-bold font-mono whitespace-nowrap transition-all cursor-pointer ${
                  selectedFormat === 'FORTINET'
                    ? isLight ? 'bg-cyan-600 text-white shadow-sm' : 'bg-cyan-500 text-cyber-dark shadow-md'
                    : isLight ? 'text-slate-600 hover:text-slate-900' : 'text-gray-400 hover:text-white'
                }`}
              >
                Fortinet FortiGate
              </button>
              <button
                onClick={() => setSelectedFormat('PALO_ALTO')}
                className={`px-3 py-1.5 rounded-lg text-xs font-bold font-mono whitespace-nowrap transition-all cursor-pointer ${
                  selectedFormat === 'PALO_ALTO'
                    ? isLight ? 'bg-cyan-600 text-white shadow-sm' : 'bg-cyan-500 text-cyber-dark shadow-md'
                    : isLight ? 'text-slate-600 hover:text-slate-900' : 'text-gray-400 hover:text-white'
                }`}
              >
                Palo Alto EDL
              </button>
              <button
                onClick={() => setSelectedFormat('AWS_WAF')}
                className={`px-3 py-1.5 rounded-lg text-xs font-bold font-mono whitespace-nowrap transition-all cursor-pointer ${
                  selectedFormat === 'AWS_WAF'
                    ? isLight ? 'bg-cyan-600 text-white shadow-sm' : 'bg-cyan-500 text-cyber-dark shadow-md'
                    : isLight ? 'text-slate-600 hover:text-slate-900' : 'text-gray-400 hover:text-white'
                }`}
              >
                AWS / Cloudflare WAF
              </button>
              <button
                onClick={() => setSelectedFormat('SURICATA')}
                className={`px-3 py-1.5 rounded-lg text-xs font-bold font-mono whitespace-nowrap transition-all cursor-pointer ${
                  selectedFormat === 'SURICATA'
                    ? isLight ? 'bg-cyan-600 text-white shadow-sm' : 'bg-cyan-500 text-cyber-dark shadow-md'
                    : isLight ? 'text-slate-600 hover:text-slate-900' : 'text-gray-400 hover:text-white'
                }`}
              >
                Snort / Suricata
              </button>
              <button
                onClick={() => setSelectedFormat('CSV')}
                className={`px-3 py-1.5 rounded-lg text-xs font-bold font-mono whitespace-nowrap transition-all cursor-pointer ${
                  selectedFormat === 'CSV'
                    ? isLight ? 'bg-cyan-600 text-white shadow-sm' : 'bg-cyan-500 text-cyber-dark shadow-md'
                    : isLight ? 'text-slate-600 hover:text-slate-900' : 'text-gray-400 hover:text-white'
                }`}
              >
                CSV Feed
              </button>
            </div>

            {/* Generated Syntax Code Box */}
            <div className="rounded-2xl bg-slate-950 border border-slate-800 p-4 font-mono text-xs overflow-x-auto max-h-[420px] shadow-inner">
              <div className="flex items-center justify-between pb-2 border-b border-white/5 text-gray-500 text-[10px]">
                <span>FIREWALL BLOCKLIST EXPORT ({selectedFormat})</span>
                <span className="text-emerald-400 font-bold">READY TO DEPLOY</span>
              </div>
              <pre className="mt-3 text-cyan-300 leading-relaxed select-all">
                {generateFirewallCode()}
              </pre>
            </div>

          </div>
        </div>

      </div>
    </ViewContainer>
  );
}
